# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 629490a6a14af9703b7123407a49ddef4abcebac801e24e598ae968dde9535e4ae51b5ee7b483471f2ef63cf1083cbdd9b74676c0aa2c558c2222d25dfb5a34b

test:
  secret_key_base: ea7fb896bfb1d49061a3d546f44f5743d757a7cab87e2dd6a80c9c9d62c9ab51cca7f61adaae309fac1a66946276891276b284dff5339503510b190d57990c17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
